[plugin]
icon = 'https://wu-clan.github.io/picx-images-hosting/logo/fba.svg'
summary = 'AI Buddy Group UI'
version = '0.0.1'
description = 'fba AI Buddy Group 插件的前端实现'
author = 'wu-clan'
tags = ['ai']
